[workspace]
resolver = "2"
members = [
    "crates/pipes-core",
    "crates/pipes-render",
    "crates/pipes-app",
    "crates/pipes-settings",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT"
authors = ["Brandon Williams"]
repository = "https://github.com/brando5393/neo_win_pipes"

[workspace.dependencies]
rand = "0.8"
rand_pcg = "0.3"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "time"] }
serde = { version = "1", features = ["derive"] }
